In [3]:
import numpy as np
import pandas as pd

Reading the dataset

In [4]:
df = pd.read_csv('/kaggle/input/datasets/asoktamang/nlp-dataset/train.csv')
df.head()

      anchor        target rating  score context
0  aralkynyl   cholesterol     1d   0.25     C09
1  aralkynyl       aralkyl     1d   0.25     C09
2  aralkynyl   heterocycle     1c   0.25     C09
3  aralkynyl          acyl     1d   0.25     C09
4  aralkynyl  heterocyclic     1c   0.25     C09

studying the dataset

In [7]:
df.describe(include= object)

                             anchor       target rating context
count                         36473        36473  36473   36473
unique                          733        29340     10     106
top     component composite coating  composition      0     H01
freq                            152           24   7471    2186

checking the null values

In [9]:
df.isna().sum()

anchor     0
target     0
rating     0
score      0
context    0
dtype: int64

checking the duplicate datas in df

In [15]:
df.duplicated().sum()

np.int64(0)